app_address: ":8080"

redis_address: "dq-redis:6379"
redis_password: ""
redis_db: 0
redis_delayed_queue: "delayed_queue"

rabbitmq_address: "amqp://dq-rabbitmq:5672"
rabbitmq_queue: "notification.created"

smtp_from: "test@local.host"
smtp_host: "dq-mailhog"
smtp_port: "1025"

poller_tick_milliseconds: 100

consumer_num_workers: 30

send_retry_attemps: 30
send_retry_delay_seconds: 2
send_retry_backoff: 2